### ISSUE TITLE
What is: 'colorful-tag: []'?

### ISSUE THREAD

**Issue by kmaustral** [rien7/obsidian-colorful-tag#43]
With the latest update, new code is inserted into YAML automatically. I don't know what this is and I fear it will change the YAML in all my files. I've disabled the plugin for the time being, but await an explanation so I can work out what is happening. I hope I can keep using this very handy plugin.

**Comment by rien7** [comment]
if you use tag details, it will **add** tag detail data into the frontmatter. 

i'm sorry that this plugin will record all the tags of the file instead of the tags which using tag details.

if you don't want the plugin modify the frontmatter, you can consider to disable "Tag Detail" in "General Setting" of this plugin.

**Comment by kmaustral** [comment]
Thanks for the reply. I find that disabling Tag Detail still allows for YAML changes, such as 
`colorful-tag:
  - {}
  - {}
  - {}
  - {}
  - {}
  - {}
  - {}
  - {}
  - {}
  - {}
  - {}
  - {}
  - {}'
The only option is to disable. Even then it continues to operate, so I need to re-start Obsidian.

**Comment by rien7** [comment]
sorry for that, does it stop writing yaml after you restarting obsidian?

**Comment by kmaustral** [comment]
Yes restarting stops this, with the app disabled.
